-- MySQL Script generated by MySQL Workbench
-- Tue Oct 15 11:14:38 2019
-- Model: Biblio Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema biblio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblio` ;
CREATE SCHEMA `biblio` ;
USE `biblio` ;

-- -----------------------------------------------------
-- Table `biblio`.`editeurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`editeurs` (
  `id_editeur` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_editeur` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_editeur`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `editeurs` WRITE;
/*!40000 ALTER TABLE `editeurs` DISABLE KEYS */;
INSERT INTO `editeurs` VALUES (1,'Édition La Découverte'),(2,'Université Laval'),(3,'Éditions Yvon Blais'),(4,'Gouvernement du Québec ministère du travai'),(5,'Presse Universitaire de France'),(6,'Guérin'),(7,'Les presses de l\'Université Laval'),(8,'Amazon'),(9,'EYROLLES'),(10,'Boréal'),(11,'Livres de poche'),(12,'Wikipédia');
/*!40000 ALTER TABLE `editeurs` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `biblio`.`sujets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`sujets` (
  `id_sujet` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `sujet` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_sujet`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `sujets` WRITE;
/*!40000 ALTER TABLE `sujets` DISABLE KEYS */;
INSERT INTO `sujets` VALUES (1,'Politique'),(2,'Antropologie'),(3,'Histoire'),(4,'Physique'),(5,'Informatique'),(6,'Chimie'),(7,'Sociologie'),(8,'Droit'),(9,'Géographie'),(10,'Psychologie');
/*!40000 ALTER TABLE `sujets` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `biblio`.`type_publications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`type_publications` (
  `id_type_publication` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_publcation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_publication`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `type_publications` WRITE;
/*!40000 ALTER TABLE `type_publications` DISABLE KEYS */;
INSERT INTO `type_publications` VALUES (1,'Web'),(2,'Livres'),(3,'Articles de presse'),(4,'Euvres Anciennes'),(5,'Ouvrages de référence'),(6,'CD - DVD'),(7,'Périodique'),(8,'Thèse'),(9,'Conférence'),(10,'Cours');
/*!40000 ALTER TABLE `type_publications` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `biblio`.`livres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`livres` (
  `id_livre` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NULL DEFAULT NULL,
  `sous_titre` VARCHAR(255) NULL DEFAULT NULL,
  `annee_publication` SMALLINT(4) NULL DEFAULT NULL,
  `nb_page` VARCHAR(45) NULL DEFAULT NULL,
  `id_editeur` INT(11) UNSIGNED NOT NULL,
  `id_sujet` INT(11) UNSIGNED NOT NULL,
  `id_type_publication` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_livre`),
  INDEX `fk_editeurs` (`id_editeur` ASC),
  INDEX `fk_sujets` (`id_sujet` ASC),
  INDEX `fk_type_publications` (`id_type_publication` ASC),
  INDEX `Idx_Annee` (`annee_publication` ASC),
  INDEX `idx_titre` (`titre` ASC),
  CONSTRAINT `fk_editeurs`
    FOREIGN KEY (`id_editeur`)
    REFERENCES `biblio`.`editeurs` (`id_editeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sujets`
    FOREIGN KEY (`id_sujet`)
    REFERENCES `biblio`.`sujets` (`id_sujet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_publications`
    FOREIGN KEY (`id_type_publication`)
    REFERENCES `biblio`.`type_publications` (`id_type_publication`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `livres` WRITE;
/*!40000 ALTER TABLE `livres` DISABLE KEYS */;
INSERT INTO `livres` VALUES (1,'L impact juridique des nouvelles dispositions de la Loi sur les normes du travail',' en matière de harcèlement psychologique sur le régime légal préexistant',2005,NULL,2,7,2),(2,'Les droits et libertés dans le contexte civil',NULL,2005,NULL,3,8,8),(3,'Politiques contre le harcèlement au travail et réflexions sur le harcèlement psychologique',NULL,2004,NULL,3,2,2),(4,'Le harcèelement sexuel au travail',NULL,1991,NULL,3,7,8),(5,'Petit manuel de géographie québécoise',NULL,1977,NULL,6,9,2),(6,'Les normes du travail','dans Collection de droit 2004-05, École du Barreau du Québec, vol. 8',2004,NULL,3,8,2),(7,'Le QuÃ©bec aujourdâ??hui, identitÃ©, sociÃ©tÃ© et culture',NULL,2003,NULL,7,7,2),(8,'À qui appartient la connaissance ?','Conférence prononcée dans le cadre d un colloque de l ACFAS',2002,NULL,2,2,9),(9,'DE LA MACHINE DE TURING aux ordinateurs modernes','Informatique fondamentale:',1999,NULL,8,5,2),(10,'TABLEAUX DE BORD DE LA SECURITÉ RÉSEAU',NULL,2010,NULL,9,5,2),(11,'Windows server 2008',NULL,2009,NULL,9,5,2),(12,'LINUX ADMINISTRATION T03 : SÉCURISER UN SERVEUR LINUX\r\n \r\nAgrandissez cette image \r\nPartagez vos propres images client\r\nEditeur: découvrez commment les clients peuvent feuilleter et chercher au coeur de ce livre.\r\nLINUX ADMINISTRATION T03','SÉCURISER UN SERVEUR LINUX',2010,NULL,9,5,2),(13,'Les Institutions politiques au Québec et au Canada',NULL,2010,NULL,10,1,2),(14,'TOUTE L\'HISTOIRE DU MONDE',NULL,2010,NULL,11,3,2),(15,'Base de données','http://fr.wikipedia.org/wiki/Base_de_donn%C3%A9es',2010,NULL,12,5,1);
/*!40000 ALTER TABLE `livres` ENABLE KEYS */;
UNLOCK TABLES;
-- -----------------------------------------------------
-- Table `biblio`.`auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`auteurs` (
  `id_auteur` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_auteur`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


LOCK TABLES `auteurs` WRITE;
#/*!40000 ALTER TABLE `auteurs` DISABLE KEYS */;
INSERT INTO `auteurs` VALUES (1,'BOURGAULT J'),(2,'BRUNELLE C.'),(3,'CANTIN J-M.'),(4,'CANTIN I.'),(5,'DRAPAUX, M.'),(6,'GAGNON, M.'),(7,'GAGNON R.'),(8,'et autres'),(9,'HIRATA H.'),(10,'Guérin, Marc-Aimé'),(11,'Weidmann Koop, Marie-Christine'),(12,'Charest, Paul'),(13,'BIANCO'),(14,'VALLOIS, Denis'),(15,'LEVIER, Laurent'),(16,'LLORENS, Cedric'),(17,'FREDDI, Philippe'),(18,'BOUCHAUDY, Jean-Fraçois'),(19,'BERNARD, André'),(20,'BARREAU, Jean-Claude'),(21,'BIGOT, Guillaume');
#/*!40000 ALTER TABLE `auteurs` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `biblio`.`auteur_livre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblio`.`auteur_livre` (
  `id_auteur` INT(11) UNSIGNED NOT NULL,
  `id_livre` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_auteur`, `id_livre`),
  INDEX `fk_auteurs_has_livres_tbl_livres` (`id_livre` ASC),
  CONSTRAINT `fk_auteurs_has_livres_livres`
    FOREIGN KEY (`id_livre`)
    REFERENCES `biblio`.`livres` (`id_livre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auteurs_has_livres_auteurs`
    FOREIGN KEY (`id_auteur`)
    REFERENCES `biblio`.`auteurs` (`id_auteur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

LOCK TABLES `auteur_livre` WRITE;
/*!40000 ALTER TABLE `auteur_livre` DISABLE KEYS */;
INSERT INTO `auteur_livre` VALUES (1,1),(2,2),(3,3),(4,3),(10,5),(7,6),(11,7),(12,8),(13,9),(14,10),(15,10),(16,10),(17,11),(18,12),(19,13),(20,14),(21,14),(22,16),(22,17);
/*!40000 ALTER TABLE `auteur_livre` ENABLE KEYS */;
UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
